[driver]
id = "signify.hue.bulb.on_off"
name = "Philips Hue On/Off Light"
manufacturer = "Signify"
version = "1.3.0"
runtime = "native"
parent = "signify.hue.bridge"

[[proxy]]
id = 1
type = "light"
primary = true
capabilities = { min_on_level = 1 }

[[property]]
name = "Light id"
type = "string"
tooltip = "The bulb's resource id on the bridge"
